# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 03:07
from __future__ import unicode_literals

from django.db import migrations

#do not run this migration if you are testing :)
def add_data(apps, schema_editor):
    pass
    # Specialty = apps.get_model("api", "Specialty")
    # Tag = apps.get_model("api", "Tag")
    # Session = apps.get_model("api", "Session")
    # Speaker = apps.get_model("api", "Speaker")

    # javascript = Specialty.objects.create(name="JavaScript")
    # elixir = Specialty.objects.create(name="Elixir")
    # sql = Specialty.objects.create(name="PostgreSQL")

    # intro = Tag.objects.create(description="100")
    # intermediate = Tag.objects.create(description="200")
    # advanced = Tag.objects.create(description="300")

    # toran = Speaker.objects.create(name="Toran")
    # brandon = Speaker.objects.create(name="Brandon")
    # jarrod = Speaker.objects.create(name="Jarrod")

    # toran.specialties.add(javascript)
    # brandon.specialties.add(elixir)
    # jarrod.specialties.add(sql)

    # one = Session.objects.create(name="intro to JS")
    # one.speakers.add(toran)
    # one.tags.add(intro)
    # one.save()

    # two = Session.objects.create(name="intermediate SQL")
    # two.speakers.add(brandon)
    # two.tags.add(intermediate)
    # two.save()

    # three = Session.objects.create(name="advanced Elixir")
    # three.speakers.add(jarrod)
    # three.tags.add(advanced)
    # three.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
